### ISSUE TITLE
node_structural_equivalence not working with multiplex networks

### ISSUE THREAD

**Issue by jaeltan** [stocnet/migraph#287]
`node_structural_equivalence()` gives an error with multiplex networks `ison_algebra` and `ison_lawfirm`: `Error in colSums(t(mat)) : 'x' must be numeric`

**Comment by Kaladani** [comment]
I had a similar issue with a multiplex network but could actually not recreate the problem with ison_algebra, only with a subset of ison_physicians. The difference is that ison_algebra stores the multiplexity in seperate (numeric) variables for each network while ison_physician has one categorical variable indicating the tie type.

```
library(migraph)
node_structural_equivalence(ison_physicians$Peoria) ## produces error
node_structural_equivalence(ison_algebra) ## produces no error
```
The difference can bee seen in `node_tie_census(ison_physicians$Peoria)` vs. `node_tie_census(ison_algebra)`.

My own inelegant solution was to change the categorical variable in multiple dummy variables: 

```
net_peoria  <- ison_physicians$Peoria
type <- tie_attribute(net_peoria)$type
typedummies <- model.matrix(~type-1)
colnames(typedummies) <- sub("type", "", colnames(typedummies))

net_peoria  <- add_tie_attribute(net_peoria, 
                                 colnames(typedummies)[1],
                                 typedummies[,1])

net_peoria  <- add_tie_attribute(net_peoria, 
                                 colnames(typedummies)[2],
                                 typedummies[,2])

net_peoria  <- add_tie_attribute(net_peoria, 
                                 colnames(typedummies)[3],
                                 typedummies[,3])

net_peoria <- net_peoria %>% tidygraph::activate(edges) %>% 
  dplyr::select(-c(type)) ### as long as type still exists
node_structural_equivalence(net_peoria) ### no error
```
Probably node_structural_equivalence() would need to detect if the network has a categorical tie variable ("type" %in% igraph::edge_attr_names(.data)) and do a similar transformation to solve this without changing the network object or node_tie_census() must ignore the categorical (type) variable.

**Comment by jhollway** [comment]
Thanks @jaeltan @Kaladani , `node_tie_census()` and `node_triad_census()` have both been fixed to work with the new multiplex format (which relies on a "type" tie attribute rather than multiple tie attributes), which restores functionality to `node_structural_equivalence()` and `node_regular_equivalence()`. This will be included in the next release, also to CRAN.
