### ISSUE TITLE
unused argument in network_reg

### ISSUE THREAD

**Issue by SimonMontfort** [stocnet/migraph#297]
Thanks for the nice package which I am currently exploring...

Running 

`networkers <- ison_networkers %>% to_subgraph(Discipline == "Sociology")`

`model1 <- network_reg(weight ~ alter(Citations) + sim(Citations), 
                      networkers, times = 20)`

from the help page `? network_reg ` on R version 4.3.2 and migraph version 1.2.1 on my MacOS Monterey 12.6 (which I should certainly update), I get 

`Error in manynet::to_uniplex(data, edge = getDependentName(formula)) : 
  unused argument (edge = getDependentName(formula))`

Why might this be?

**Comment by jhollway** [comment]
Most recent version of migraph is 1.4.1. Note that from v1.4 onwards, the function has been renamed `net_regression()` to be consistent with the rest of the package and manynet. It will also gently warn you that for a directed network like `ison_networkers` and including `sim()` among the terms, one should also include `ego(Citations)`.
